name: Docker Image CI

on:
  push:
    branches: [ "build-docker-image" ]
  pull_request:
    branches: [ "build-docker-image" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Pull the Python image
      run: docker pull python:3.11
      
    - name: Build the Docker image
      run: docker build -t fastapi-app:$(date +%s) .
