name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package Application
        run: |
          rm -rf temp_package  # Ensure previous package folder is removed
          mkdir temp_package
          rsync -av --exclude=temp_package --exclude=venv --exclude=deployment-package.zip . temp_package/
          cd temp_package
          zip -r ../deployment-package.zip .
          cd ..

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name fastapi-lambda --zip-file fileb://deployment-package.zip

